repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.292"
    hooks:
      - id: ruff
        exclude: docs/source/conf.py|ipynb_filter.py
        args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        exclude: ipynb_filter.py|docs/source/conf.py
        additional_dependencies:
          - types-setuptools
          - types-tqdm
          - pandas-stubs
          - types-psutil
