name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  - adaptive >=0.11
  - cloudpickle
  - dill
  - ipyparallel
  - jinja2
  - loky
  - mpi4py
  - mpich
  - numpy
  - pandas
  - psutil
  - pyarrow
  - pyzmq
  - structlog
  - tinydb
  - toolz
  - tqdm
