name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  - mpi4py
  - mpich
  - adaptive >= 0.14.1
  - cloudpickle
  - dill
  - ipyparallel
  - jinja2
  - loky
  - numpy
  - pandas
  - psutil
  - pyarrow
  - pyzmq
  - rich
  - structlog
  - tinydb
  - toolz
  - tqdm
  - versioningit
  # optional-dependencies: all
  - dask-mpi
  - mpi4py
  # optional-dependencies: test
  - pytest
  - pytest-asyncio
  - coverage
  - pytest-cov
