name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  - adaptive >=0.14.1
  - cloudpickle
  - dill
  - ipyparallel
  - jinja2
  - loky
  - mpi4py
  - mpich
  - numpy
  - pandas
  - psutil
  - pyarrow
  - pyzmq
  - rich
  - structlog
  - tinydb
  - toolz
  - tqdm
  - versioningit
  - pip:
      - m2r @ git+https://github.com/crossnox/m2r@dev#egg=m2r  # https://github.com/sphinx-doc/sphinx/issues/7420#issuecomment-610958327
