name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  # Required deps from pyproject.toml
  - adaptive >=0.14.1
  - cloudpickle
  - dill
  - ipyparallel
  - jinja2
  - loky
  - mpi4py
  - mpich
  - numpy
  - pandas
  - psutil
  - pyarrow
  - pyzmq
  - rich
  - structlog
  - tinydb
  - toolz
  - tqdm
  - versioningit
  # optional-dependencies: all
  - dask-mpi
  - mpi4py
  # optional-dependencies: test
  - pytest
  - pytest-asyncio
  - coverage
  - pytest-cov
  # optional-dependencies: docs
  - myst-nb
  - sphinx_fontawesome
  - sphinx
  - furo
  - myst-parser
  - emoji
