name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      - name: Install adaptive-scheduler
        shell: bash -l {0}
        run: |
          pip install -e ".[test,all]"

      # Linux and macOS
      - name: Run Python
        shell: bash -l {0}
        run: |
          python -c "import adaptive_scheduler; print(adaptive_scheduler.__version__)"
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
