name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      # Linux and macOS
      - name: Run Python
        shell: bash -l {0}
        run: |
          python -c "import adaptive_scheduler; print(adaptive_scheduler.__version__)"
